# Use slim Python image
FROM python:3.12-slim

# Install dependencies
RUN apt-get update && \
    apt-get install -y git && \
    pip install --no-cache-dir gradio PyGithub GitPython python-slugify && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install python-dotenv
RUN git config --global --add safe.directory /project 

# Set working directory
WORKDIR /project

# Default command (runs your script)
CMD ["python", "hugo_blog_manager.py"]
